[package]
name = "example_plugin"
version = "0.1.0"
edition = "2021"

[dependencies]
libspkg = { git = "https://github.com/Strawberry-Foundations/libspkg", features = ["plugin"]}

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = 'z'
strip = true
lto = true