[package]
name = "example_plugin"
version = "0.1.2"
edition = "2021"

[dependencies]
libspkg = { version = "0.1.6", features = ["plugin"]}

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = 'z'
strip = true
lto = true