[package]
name = "advanced_plugin"
version = "0.1.0"
edition = "2021"

[dependencies]
libspkg = { version = "0.1.6", features = ["plugin"]}
lazy_static = "1.5.0"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = 'z'
strip = true
lto = true