name: Build & publish plugins (x86_64)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build plugins
        run: bash build_all.sh

      - uses: actions/upload-artifact@v4
        with:
          name: spkg-plugins
          path: |
            releases/

      - uses: softprops/action-gh-release@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "latest"
          prerelease: false
          name: "Latest plugin releases for x86_64"
          files: |
            releases/*